### PR TITLE
line 525: Fix sheet_file assignment to work for schematics outside current directory

### PR DESCRIPTION
**Pull request by 4b11b4**
I've followed the directions from the "Contributing" file, but:
- I don't know how to make a test for this change.
- I set up the virtualenv and ran the "python setup.py develop" -- which I believe installs the proper dependencies?
- flake8 kifield/kifield.py already fails in various places, none of which are on line 525
- python setup.py tests runs 0 tests, not sure why
- tox is unable to find python3.4, python3.6 and pypy

I'm happy to work these problems out. I use KiField very often and would be happy to support.

### CODE REVIEW

**Comment by 4b11b4** [comment]
Is this still relevant?

**Comment by kasbah** [comment]
Is the change still needed for your own use? I would say it's still relevant then. I think it would be ok to skip an automated test for this if you can't think of anything. I don't have merge privileges though. 

We should also try and fix up the test suite to make it easier for future contributions.

**Comment by 4b11b4** [comment]
I still need it, yes. It occurs in the situation where you have nested hierarchical schematics and no symbols exist at one of those levels.

For example,
I often have my main schematic... "**proj.sch**"
**proj.sch** has an **led.sch** which then has a bunch of hierarchical blocks of different types of LED indicator circuits.
_No symbols exist inside_ **led.sch**, and thus, this fix is needed.

The pull request I made is actually from the issue someone else opened, it is their fix.

**Comment by xesscorp** [comment]
Thanks for the fix!

**Comment by 4b11b4** [comment]
Thanks for all of the hours you've saved me!

**Pull request merged**
