### PR TITLE
Implement grouped output

### PR DESCRIPTION
**Pull request by kasbah**
This will be the final step for finishing off #5 (and #8) by allowing _output_ of grouped BOMs. This is based on #20 as I find TDD easier for this kind of thing.

### CODE REVIEW

**Comment by kasbah** [comment]
This is implemented now, and seems to work. Not done extensive testing beyond the automated stuff. Is it a problem that it creates a new workbook each time it groups? Is some of the formatting supposed to be passed along for xlsx inserting? 

It makes sense to me to have this as the default but we could put it behind an option. What do you think?

**Comment by kasbah** [comment]
I forgot to add the tests for `group_wb` and I may have lost them, let me recover or re-write them.

**Comment by kasbah** [comment]
Ok, I added the tests. Should be good to go now unless you have any comments or suggestions.

**Comment by xesscorp** [comment]
This branch is failing 3 of the 4 end-to-end tests. There needs to be an option for turning off grouping so I can see if the tests will pass in that case.

**Comment by kasbah** [comment]
Ok, I added the switch.

**Comment by xesscorp** [comment]
Thanks for the --group option. It passes my end-to-end test now.

**Comment by kasbah** [comment]
You mean when you disable the feature I added? :laughing: I would really appreciate it if you documented how to run these end-to-end tests. Would be good to add some that make use of this feature.

**Comment by xesscorp** [comment]
You can run the end-to-end tests by going into the `tests` dirtectory and running `make -f test.mk`. I also added comments to `test.mk` to give some indication of what's going on.

**Pull request merged**
